export declare const usage: import("@mantine/ds").MantineDemo, multiple: import("@mantine/ds").MantineDemo, deselect: import("@mantine/ds").MantineDemo, range: import("@mantine/ds").MantineDemo, singleRange: import("@mantine/ds").MantineDemo, numberOfColumns: import("@mantine/ds").MantineDemo, sizeConfigurator: import("@mantine/ds").MantineDemo;
export { controlledDate } from './DatePicker.demo.controlledDate';
export { controlProps } from './DatePicker.demo.controlProps';
export { defaultDate } from './DatePicker.demo.defaultDate';
export { labelFormat } from './DatePicker.demo.labelFormat';
export { listFormat } from './DatePicker.demo.listFormat';
export { locale } from './DatePicker.demo.locale';
export { maxLevel } from './DatePicker.demo.maxLevel';
export { minMax } from './DatePicker.demo.minMax';
export { defaultLevel } from './DatePicker.demo.defaultLevel';
export { firstDayOfWeek } from './DatePicker.demo.firstDayOfWeek';
export { weekendDays } from './DatePicker.demo.weekendDays';
export { renderDay } from './DatePicker.demo.renderDay';
export { hideWeekdays } from './DatePicker.demo.hideWeekdays';
export { hideOutsideDates } from './DatePicker.demo.hideOutsideDates';
